[server]
headless = true
address = "0.0.0.0"
port = 8501  # Set this to 8501, which is the default port for Streamlit

[theme]
primaryColor = "#2E7D32"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F4F1"
textColor = "#262730"
font = "sans-serif"
